FROM node:20-alpine
RUN apk add --no-cache libc6-compat
RUN npm install -g pnpm
WORKDIR /app
COPY . .
RUN pnpm install
RUN ls -la frontend/node_modules/.bin
RUN ls -la frontend/node_modules/next
RUN pnpm --filter frontend run build
