FROM node:20-alpine

# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat

# Install pnpm
RUN npm install -g pnpm

# Set working directory
WORKDIR /app

# Copy the entire monorepo
COPY . .

# Install dependencies
RUN pnpm install

# Build the Next.js frontend
RUN pnpm --filter frontend run build

# Start the Next.js frontend
WORKDIR /app/frontend
EXPOSE 3000

CMD ["pnpm", "run", "start"]
