packages:
  - "primary-backend"
  - "hooks"
  - "database"
  - "frontend"
  - "sweeper"
  - "worker"
  - "poller"
allowBuilds:
  '@google/genai': false
  esbuild: true
  protobufjs: false
  sharp: false
  unrs-resolver: false
