apiVersion: apps/v1
kind: Deployment
metadata:
  name: hooks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hooks
  template:
    metadata:
      labels:
        app: hooks
    spec:
      containers:
      - name: hooks
        image: yuvraj2130/zapier-backend:latest
        args: ["pnpm", "--filter", "hooks", "run", "dev"]
        ports:
        - containerPort: 3002
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_DB
        - name: DATABASE_URL
          value: "postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres-service:5432/$(POSTGRES_DB)"
